name: build-raspberry
run-name: ${{ github.actor }} is building OpenSprinkler for RaspberryPI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./open-sprinkler    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        id: build_image
        uses: pguyot/arm-runner-action@v2
        with:
          commands: |
            ./build.sh
            ls -l build/
            sudo fdisk -l
            pwd
      - name: Extract build artifacts
        run: |
          mkdir test
          mount -o loop,ro,offset=32256 ${{ steps.build_image.outputs.image }} ./test
          ls -l ./test/
      - name: Compress the release image
        # if: github.ref == 'refs/heads/releng' || startsWith(github.ref, 'refs/tags/')
        run: |
          mv ${{ steps.build_image.outputs.image }} my-release-image.img
          xz -0 -T 0 -v my-release-image.img
      - name: Upload release image
        uses: actions/upload-artifact@v3
        # if: github.ref == 'refs/heads/releng' || startsWith(github.ref, 'refs/tags/')
        with:
          name: Release image
          path: my-release-image.img.xz
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OpenSprinkler
          path: |
            open-sprinkler/build
